# docker-compose.yml
services:
  api:
    build:
      context: .  # build.context をプロジェクトルートに設定
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000" # ホストの8000番をコンテナの8000番にマッピング
    volumes:
      - .:/code  # ホストのコードをコンテナにマウント（ホットリロード用）
    working_dir: /code
    environment:
      - PYTHONPATH=/code/app
    
    # 開発用: Code変更をHot reload
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload # command に --reload を追加して開発用に設定

  gradio:
    build:
      context: .
      dockerfile: docker/Dockerfile.gradio
    ports:
      - "7860:7860"
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - PYTHONPATH=/code/app

    # commandはDockerfileのCMDをそのまま使う（必要なら上書き）
    #command: python app/gradio_ui.py